clear all
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\kwira\Downloads\Keep Light No Turns vs Remove Light No Turns.csv
%
% Auto-generated by MATLAB on 12-Jul-2021 11:12:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["wavelength", "RemoveLightNoTurns", "KeepLightNoTurns"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Day1 = readtable("C:\Users\kwira\Downloads\Keep Light No Turns vs Remove Light No Turns.csv", opts);

%% Convert to output type
Day1 = table2cell(Day1);
numIdx = cellfun(@(x) ~isnan(str2double(x)), Day1);
Day1(numIdx) = cellfun(@(x) {str2double(x)}, Day1(numIdx));

%% Clear temporary variables
clear opts

%%
sz = size(Day1);
szz = sz(1,2);
szzz = sz + 1;
x = Day1(:,1);
xx = cell2mat(x);
n = 2;

while n ~= szzz
    y = Day1(:,n);
    yy = cell2mat(y);
    trial = n - 1;
    plot(xx,yy,'-')
    hold on
    n = n + 1;
end

title('Light No Turns - Keep vs Remove','fontsize',16)
xlabel('Wavelength [nm]','fontsize',16)
ylabel('Percent Tranmission','fontsize',16)

%%
xlim([200, 1100]);
legend show;

%{
line([200,200],[0,100],'color','b','linewidth',1)
line([600,600],[0,100],'color','b','linewidth',1)
%}